analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - lib/tv/providers/android_tv/protocol/generated/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    unawaited_futures: true
